#!/bin/sh
sudo systemctl stop kpu1
sudo systemctl stop kpu2
sudo systemctl stop kpu3
sudo systemctl stop kpu4
sudo systemctl stop kpu5
sudo systemctl stop kpu6

sleep 2

sudo killall php
sudo killall php
sudo killall 03_loop_suara.sh
sudo killall 03_loop_suara.sh



